# Every class-*.ps1 under POSH-Oceanstor/Private must appear here.
# Add the class name when creating a new class file; the ModuleInventory
# Pester suite fails when any class file is absent from this list.
@{
    Classes = @(
        'OceanStorAlarm'
        'OceanStorBBU'
        'OceanStorCIFSShare'
        'OceanStorController'
        'OceanStorDisks'
        'OceanStorFileSystem'
        'OceanStorHost'
        'OceanStorHostGroup'
        'OceanStorHostLink'
        'OceanStorLunGroup'
        'OceanStorMappingView'
        'OceanStorNFSShare'
        'OceanStorPortEth'
        'OceanStorPortFc'
        'OceanStorStoragePool'
        'OceanStorSystem'
        'OceanStorViewHost'
        'OceanStorvStore'
        'OceanStorvlLan'
        'OceanstorDtree'
        'OceanstorEnclosure'
        'OceanstorFileSystemSnapshot'
        'OceanstorHostinitiatorFC'
        'OceanstorHostinitiatorISCSI'
        'OceanstorHostinitiatorNVMe'
        'OceanstorInterfaceModule'
        'OceanstorLIF'
        'OceanstorLunSnapshot'
        'OceanstorLunv3'
        'OceanstorLunv6'
        'OceanstorNFSclient'
        'OceanstorPortBond'
        'OceanstorPortGroup'
        'OceanstorPortSAS'
        'OceanstorProtectionGroup'
        'OceanstorQuota'
        'OceanstorSession'
        'OceanstorSnapshotConsistencyGroup'
        'OceanstorViewStorage'
        'OceanstorWorkload'
    )
}
